-- ORBI Phase B.3 — extend exchange_rates.provenance to allow on-demand-resolve
--
-- The on-demand-resolve Edge Function (orbi/edge-functions/on-demand-resolve)
-- computes rates for arbitrary minutes on request from V3 / OWM / OWB. Rows
-- it writes are tagged provenance = 'on-demand-resolve' so we can scope
-- rollbacks or analytics to that path without disturbing the live forward-fill.
--
-- Discovery of current constraint name:
--   The constraint was created inline by migration 005_add_provenance_column.sql
--   as part of the column definition. Postgres auto-named it. To verify the
--   actual name before applying this migration, run:
--
--     SELECT conname FROM pg_constraint
--      WHERE conrelid = 'exchange_rates'::regclass
--        AND contype = 'c'
--        AND pg_get_constraintdef(oid) ILIKE '%provenance%';
--
--   The autogenerated name is typically `exchange_rates_provenance_check`.
--   If different on PROD, substitute the real name in the DROP CONSTRAINT line.

ALTER TABLE exchange_rates DROP CONSTRAINT IF EXISTS exchange_rates_provenance_check;

ALTER TABLE exchange_rates
  ADD CONSTRAINT exchange_rates_provenance_check
  CHECK (provenance IN (
    'forward-fill',
    'historical-backfill',
    'reconciler-upgrade',
    'composite-replay',
    'on-demand-resolve'
  ));

COMMENT ON CONSTRAINT exchange_rates_provenance_check ON exchange_rates IS
  'Allowed provenance tags. Extended in migration 007 to include on-demand-resolve (the Edge Function path that computes rates for any minute on request).';
