project_id = "gposxxmxenrdvewrprle"

[functions.or-providers]
verify_jwt = false

[functions.or-platform-display]
verify_jwt = false

[functions.or-link-mint-token]
verify_jwt = false

[functions.or-link-complete]
verify_jwt = false
