/**
 * CCXT base , shared adapter scaffolding for the 100+ exchanges that
 * CCXT (https://github.com/ccxt/ccxt) wraps behind a unified interface.
 *
 * Strategy: instead of writing one adapter per exchange (n x person-hours),
 * we write ONE adapter that knows how to talk to any CCXT-supported
 * exchange. Each per-exchange entry in dispatch.ts becomes a thin
 * `makeCcxtAdapter({ slug, exchangeId, ... })` call.
 *
 * Adding the next exchange:
 *   1. Pick a CCXT exchange id (see https://github.com/ccxt/ccxt#exchanges)
 *   2. Add `makeCcxtAdapter({...})` call to dispatch.ts
 *   3. Done , discovery, sync, credential schema all auto-derived
 *
 * Per-exchange discovery is intentionally minimal: returns one synthetic
 * wallet entry per exchange. Trades + deposits + withdrawals across all
 * the user's assets get synced under that single wallet, which the
 * consumer (V2/V3/OW) can group by asset on the inbound side. This avoids
 * the O(N) discovery problem where N = number of asset balances the user
 * holds (CCXT's fetchBalance returns every asset including dust).
 *
 * Per-exchange credential schemas are derived from the manifest's
 * credentialShape field (generated by generate-ccxt-manifest.mjs via
 * CCXT's requiredCredentials introspection). The hardcoded
 * CCXT_CREDENTIAL_FIELDS map below is kept as a legacy fallback for
 * callers that predate the credentialShape field on CcxtAdapterConfig.
 *
 * Sync pulls (when the exchange supports it , checked via `exchange.has`):
 *   - Trades       => type='trade'
 *   - Deposits     => type='deposit',    direction='in'
 *   - Withdrawals  => type='withdrawal', direction='out'
 *
 * NOT in v1 (deliberate scope cuts):
 *   - Per-asset wallet enumeration (today: one synthetic wallet per exchange)
 *   - Margin / futures positions (only spot trades for now)
 *   - Fee-as-separate-tx emission (today: fee is recorded in the trade
 *     but not split into its own NormalizedTransaction)
 *   - Per-symbol cursor tracking (today: single cursor across all symbols
 *     for trades , relies on CCXT's `since` param and consumer dedup)
 *
 * Cursor: highest tx timestamp (unix ms) seen across all three streams.
 * Persisted as a string of the millisecond integer.
 *
 * Bundle / load strategy: the CCXT module is imported DYNAMICALLY at
 * sync time only. Importing it at module-init load time was crashing
 * the /or-providers manifest endpoint (500) because some CCXT subpath
 * fails under esm.sh's transform inside Deno's edge-function runtime.
 * Lazy import keeps the manifest path totally insulated from CCXT
 * load failures , only sync paths actually need the package.
 *
 * Credential field schemas are derived from the manifest's credentialShape
 * field when available (see CcxtAdapterConfig.credentialShape). The
 * CCXT_CREDENTIAL_FIELDS map below is the legacy fallback for callers
 * that don't pass credentialShape.
 */

// deno-lint-ignore-file no-explicit-any
import type {
  ProviderAdapter,
  DiscoveredWallet,
  NormalizedTransaction,
  SyncResult,
  CredentialField,
} from '../types.ts';
import { classifyUpstreamError, errorClassName } from '../../upstream-errors.ts';

// --- Per-exchange config -------------------------------------------------

export interface CcxtAdapterConfig {
  /** OR provider slug (the value stored in connections.provider_type). */
  slug: string;
  /** CCXT exchange id (binance, coinbase, kraken, etc.). */
  exchangeId: string;
  /** Display name in the picker. */
  displayName: string;
  /** Subtitle for the picker tile. */
  description?: string;
  /** Filter chips / search keywords. */
  tags?: string[];
  /** Sort weight inside category. */
  popularity?: number;
  /**
   * Credential shape from the manifest (generated by generate-ccxt-manifest.mjs).
   * When set, this drives buildCredentialFields directly and is authoritative.
   * Sourced from CCXT's requiredCredentials introspection at manifest generation
   * time, so it is always accurate for the pinned ccxt version.
   *
   * When omitted, buildCredentialFields falls back to the hardcoded
   * CCXT_CREDENTIAL_FIELDS map below (legacy path).
   */
  credentialShape?: 'apiKey+secret' | 'apiKey+password+secret' | 'apiKey+secret+uid';
  /**
   * Exchange capabilities from the CCXT manifest, introspected at manifest
   * generation time. Optional: absent means unknown, not false.
   */
  capabilities?: { trades: boolean; deposits: boolean; withdrawals: boolean };
}

// --- Credential field schemas --------------------------------------------
//
// Three field sets covering the three ALLOWED_CRED_SHAPES that OR wires.
// The manifest's credentialShape field picks between them at adapter
// construction time, so no per-exchange hardcoding is needed for new
// exchanges as long as they go through dispatch.ts.

const APIKEY_SECRET: CredentialField[] = [
  { name: 'apiKey', type: 'secret', label: 'API key', placeholder: 'From the exchange API settings' },
  { name: 'secret', type: 'secret', label: 'API secret', placeholder: 'From the exchange API settings' },
];

const APIKEY_SECRET_PASSPHRASE: CredentialField[] = [
  ...APIKEY_SECRET,
  {
    name: 'password',
    type: 'secret',
    label: 'API passphrase',
    placeholder: 'The passphrase you set when creating the API key',
  },
];

const APIKEY_SECRET_UID: CredentialField[] = [
  ...APIKEY_SECRET,
  {
    name: 'uid',
    type: 'string',
    label: 'User ID (UID)',
    placeholder: 'Your exchange-side account UID',
  },
];

// Legacy hardcoded map -- kept as a fallback for callers that predate the
// credentialShape field on CcxtAdapterConfig. When dispatch.ts passes
// credentialShape, this map is not consulted.
//
// Note: bitstamp was historically apiKey+secret+uid in CCXT but moved to
// apiKey+secret in ccxt@4.4.30; the manifest reflects the current state.
// For any exchange going through dispatch.ts, the manifest value wins.
const CCXT_CREDENTIAL_FIELDS: Record<string, CredentialField[]> = {
  // apiKey + secret only
  kraken: APIKEY_SECRET,
  binance: APIKEY_SECRET,
  bybit: APIKEY_SECRET,
  gemini: APIKEY_SECRET,
  bitfinex: APIKEY_SECRET,
  cryptocom: APIKEY_SECRET,
  ndax: APIKEY_SECRET,
  bitbuy: APIKEY_SECRET,
  // apiKey + secret + passphrase
  coinbase: APIKEY_SECRET_PASSPHRASE,
  okx: APIKEY_SECRET_PASSPHRASE,
  kucoin: APIKEY_SECRET_PASSPHRASE,
  bitget: APIKEY_SECRET_PASSPHRASE,
  blofin: APIKEY_SECRET_PASSPHRASE,
  coincatch: APIKEY_SECRET_PASSPHRASE,
  coinbaseexchange: APIKEY_SECRET_PASSPHRASE,
  coinbaseinternational: APIKEY_SECRET_PASSPHRASE,
  // apiKey + secret + uid
  bitmart: APIKEY_SECRET_UID,
  coinmate: APIKEY_SECRET_UID,
};

/**
 * Derive credential fields for an exchange.
 *
 * Primary path: use credentialShape from the manifest (authoritative,
 * covers all 98 wired exchanges). Falls back to the hardcoded map for
 * callers that predate the credentialShape field, then to APIKEY_SECRET
 * as the safe default (works for the majority of exchanges).
 */
function buildCredentialFields(
  exchangeId: string,
  credentialShape?: 'apiKey+secret' | 'apiKey+password+secret' | 'apiKey+secret+uid',
): CredentialField[] {
  if (credentialShape) {
    switch (credentialShape) {
      case 'apiKey+password+secret': return APIKEY_SECRET_PASSPHRASE;
      case 'apiKey+secret+uid': return APIKEY_SECRET_UID;
      default: return APIKEY_SECRET;
    }
  }
  // Legacy fallback: hardcoded map, then safe default.
  return CCXT_CREDENTIAL_FIELDS[exchangeId] ?? APIKEY_SECRET;
}

// --- CCXT instance construction (lazy) -----------------------------------

/**
 * Dynamic import of CCXT , runs only when sync actually fires. Failure
 * here surfaces as a sync error on the affected connection rather than
 * taking down /or-providers / the rest of the edge-function bundle.
 */
async function instantiateExchange(
  exchangeId: string,
  credentials: Record<string, unknown>,
): Promise<any> {
  let ccxtModule: any;
  try {
    // npm: specifier -- Deno native resolver, no external CDN hop (DL-0495).
    ccxtModule = await import('npm:ccxt@4.4.30');
  } catch (err) {
    throw new Error(
      `[ccxt:${exchangeId}] failed to load ccxt package: ${err instanceof Error ? err.message : String(err)}`,
    );
  }
  // Deno npm: specifier may expose the module under .default -- try both.
  const ExchangeClass = ccxtModule[exchangeId] ?? ccxtModule.default?.[exchangeId];
  if (typeof ExchangeClass !== 'function') {
    throw new Error(`[ccxt:${exchangeId}] unknown CCXT exchange id (not exposed on package)`);
  }
  const config: Record<string, unknown> = {
    enableRateLimit: true, // let CCXT throttle requests automatically
    timeout: 15000, // 15 s hard limit per request; matches the ccxt-stress harness
  };
  for (const field of ['apiKey', 'secret', 'password', 'uid', 'walletAddress', 'privateKey']) {
    if (typeof credentials[field] === 'string' && (credentials[field] as string).length > 0) {
      config[field] = credentials[field];
    }
  }
  return new ExchangeClass(config);
}

// --- Discovery -----------------------------------------------------------

/**
 * One synthetic wallet per exchange. The user picks the wallet in the OR
 * widget; per-asset enumeration happens during sync (CCXT methods
 * naturally span all assets the API key can see).
 *
 * Discovery now runs server-side in or-discover-wallets, so CORS is no
 * longer a constraint. We validate credentials before returning a wallet:
 * a wallet that fails on every subsequent sync is worse than a clear error
 * during connection setup.
 *
 * Validation: call fetchBalance (the most broadly supported auth-requiring
 * CCXT method). If the exchange does not advertise it, we reject at discovery
 * with UPSTREAM_UNSUPPORTED so callers get a clear failure immediately rather
 * than accepting a wallet that will fail every subsequent sync.
 *
 * Error taxonomy: UPSTREAM_AUTH_FAILED, UPSTREAM_UNAVAILABLE,
 * UPSTREAM_RATE_LIMITED, and UPSTREAM_UNSUPPORTED are preserved as distinct codes. The caller
 * (or-discover-wallets) maps them to HTTP status and customer copy via the
 * error catalog. A bad key must NOT look like a downed exchange.
 */
function buildDiscover(slug: string, exchangeId: string) {
  return async function discoverWallets(
    credentials: Record<string, unknown>,
  ): Promise<DiscoveredWallet[]> {
    const exchange = await instantiateExchange(exchangeId, credentials);

    // `accountKey` is set when fetchBalance succeeds. It is a stable fingerprint
    // for reconnect deduplication: or-link-complete can tell a reconnect from a
    // new connect. Exchanges that do not advertise fetchBalance are rejected at
    // discovery (see else-branch below): they throw UPSTREAM_UNSUPPORTED rather
    // than returning a wallet that would fail on every subsequent sync.
    let accountKey: string | undefined;

    if (exchange.has?.fetchBalance) {
      try {
        await exchange.fetchBalance();
        // fetchBalance succeeded: compute a stable, non-reversible fingerprint for
        // reconnect dedup. sha256(exchangeId + ":" + apiKey) is unique per account
        // and never leaves the server (discovery_sessions is service-role only).
        // This records that fetchBalance ran for this exchange, not that all
        // exchanges enforce it (see else-branch for those that skip it).
        const keyMaterial = `${exchangeId}:${String(credentials.apiKey ?? '')}`;
        const hashBuf = await crypto.subtle.digest('SHA-256', new TextEncoder().encode(keyMaterial));
        accountKey = Array.from(new Uint8Array(hashBuf))
          .map((b) => b.toString(16).padStart(2, '0'))
          .join('');
      } catch (raw) {
        const err = raw instanceof Error ? raw : new Error(String(raw));
        const code = classifyUpstreamError(err.message, errorClassName(err));
        // Tag the rethrown error so or-discover-wallets can return the right
        // HTTP status and customer copy without collapsing distinct codes.
        const out = new Error(`[ccxt:${exchangeId}] discover credential check: ${code}`);
        (out as any).upstreamCode = code;
        throw out;
      }
    } else {
      // Exchange does not advertise fetchBalance. Reject at discovery so callers
      // get a distinct error code (UPSTREAM_UNSUPPORTED) rather than accepting a
      // wallet that will fail every subsequent sync. This should be rare:
      // fetchBalance is supported by virtually all CCXT exchanges that require
      // authentication. A thrown error at discovery surfaces a meaningful
      // rejection immediately instead of deferring failure to the first sync.
      const unsupported = new Error(
        `[ccxt:${exchangeId}] discover: exchange does not advertise fetchBalance: UPSTREAM_UNSUPPORTED`,
      );
      (unsupported as any).upstreamCode = 'UPSTREAM_UNSUPPORTED';
      throw unsupported;
    }

    return [
      {
        external_wallet_id: slug,
        ...(accountKey !== undefined ? { account_key: accountKey } : {}),
        currency: 'USD', // exchange wallets are multi-currency; this is the display default
        label: `${slug} account`,
      },
    ];
  };
}

// --- Sync ----------------------------------------------------------------

/**
 * What one pass over the three CCXT sources produced.
 *
 * `denied` names the sources that answered but refused to hand over data.
 * The caller turns a non-empty list into `partial: true` so a connection is
 * never reported healthy over history nobody was allowed to read.
 *
 * Sources skipped as NotSupported are deliberately NOT listed here. CCXT
 * simply has no implementation for those, it is a fixed property of the
 * exchange rather than a fault, and it was already being skipped silently.
 * Counting them would flip a large number of currently healthy connections
 * to `partial` on deploy for a reason no customer can act on.
 */
export interface CcxtSourceSweep {
  transactions: NormalizedTransaction[];
  denied: string[];
}

/**
 * Decide whether one source's failure should end the whole sync.
 *
 * Survivable, and neither says anything about the other two sources:
 *
 *   NotSupported      CCXT does not implement this call for this exchange,
 *                     or not without a symbol. Skipped since the adapter
 *                     was written.
 *   PermissionDenied  The credential is valid but lacks the scope this one
 *                     endpoint needs. A read-only Bitstamp key hits exactly
 *                     this on `fetchWithdrawals`, which posts to
 *                     /v2/withdrawal-requests/: Bitstamp answers "No
 *                     permission found" and CCXT raises PermissionDenied.
 *
 * Everything else still throws, deliberately:
 *
 *   AuthenticationError  The credential itself is rejected, so every source
 *                        would fail. "Reconnect this account" is then the
 *                        right advice, and a partial success would bury it.
 *   Rate limits, outages Transient. Recording a partial success advances the
 *                        cursor past rows that were never read, and the next
 *                        sync starts after them. Failing is what makes the
 *                        retry fetch them.
 */
function isSurvivableSourceError(e: unknown): 'unsupported' | 'denied' | null {
  const cls = e instanceof Error ? errorClassName(e) : '';
  const msg = e instanceof Error ? e.message : String(e);
  if (cls === 'NotSupported' || /NotSupported/i.test(msg)) return 'unsupported';
  if (cls === 'PermissionDenied') return 'denied';
  return null;
}

/**
 * Stream three CCXT data sources (trades, deposits, withdrawals) into one
 * combined NormalizedTransaction list. Each source contributes only what
 * the exchange's `has` map says it supports.
 *
 * A source that is refused is skipped and named, not fatal. Before this, one
 * refused source threw and discarded the rows the other sources had already
 * returned successfully, so a Bitstamp key that could read its whole trade
 * history synced nothing at all and reported an auth failure.
 *
 * The exception is a sweep where EVERY attempted source was refused. Nothing
 * was read, so there is no data to protect, and a hard failure carries more
 * information to the customer than an empty partial success.
 *
 * `since` is unix ms , what CCXT expects as its `since` parameter.
 */
export async function fetchAllSince(
  exchange: any,
  exchangeId: string,
  since: number | undefined,
): Promise<CcxtSourceSweep> {
  const out: NormalizedTransaction[] = [];
  const denied: string[] = [];
  let attempted = 0;
  let skippedAny = 0;
  let firstDenial: unknown = null;

  /**
   * Run one source, absorbing only the failures classified as survivable.
   *
   * `source` is the domain word that reaches the wire ("withdrawals"), kept
   * separate from `method` so the published contract does not pin itself to
   * a CCXT method name we might one day stop calling. Both are OR's own
   * vocabulary, never upstream text, so both are safe to log.
   */
  async function sweep(source: string, method: string, run: () => Promise<void>): Promise<void> {
    attempted++;
    try {
      await run();
    } catch (e) {
      const kind = isSurvivableSourceError(e);
      if (kind === null) throw e;
      skippedAny++;
      if (kind === 'denied') {
        denied.push(source);
        if (firstDenial === null) firstDenial = e;
      }
      console.warn(
        `[ccxt:${exchangeId}] ${method} ${kind === 'denied' ? 'refused by the provider (missing key permission)' : 'unsupported'}; skipping`,
      );
    }
  }

  // ---- Trades ----------------------------------------------------------
  if (exchange.has?.fetchMyTrades) {
    await sweep('trades', 'fetchMyTrades', async () => {
      // Pass undefined symbol to fetch all symbols at once. Most major
      // exchanges support this (Binance, Coinbase, Kraken, etc.). If a
      // specific exchange requires a symbol, CCXT throws NotSupported and
      // we skip , v1.1 will iterate over the user's balance assets to
      // build symbols when no-arg trades aren't supported.
      const trades = await exchange.fetchMyTrades(undefined, since, 500);
      for (const t of trades ?? []) {
        out.push(normalizeTrade(t, exchangeId));
      }
    });
  }

  // ---- Deposits --------------------------------------------------------
  if (exchange.has?.fetchDeposits) {
    await sweep('deposits', 'fetchDeposits', async () => {
      const deposits = await exchange.fetchDeposits(undefined, since, 500);
      for (const d of deposits ?? []) {
        out.push(normalizeTransfer(d, 'deposit', 'in', exchangeId));
      }
    });
  }

  // ---- Withdrawals -----------------------------------------------------
  if (exchange.has?.fetchWithdrawals) {
    await sweep('withdrawals', 'fetchWithdrawals', async () => {
      const withdrawals = await exchange.fetchWithdrawals(undefined, since, 500);
      for (const w of withdrawals ?? []) {
        out.push(normalizeTransfer(w, 'withdrawal', 'out', exchangeId));
      }
    });
  }

  // Nothing was read at all and at least one source was refused: the key can
  // see nothing, so rethrow and let the caller classify it rather than
  // reporting a partial sync of zero rows. There is no data to protect here,
  // and a real error tells the customer more than an empty success.
  if (firstDenial !== null && attempted > 0 && skippedAny === attempted && out.length === 0) {
    throw firstDenial;
  }

  return { transactions: out, denied };
}

/**
 * Normalize a CCXT Trade (https://docs.ccxt.com/#/?id=trade-structure).
 *
 * For accounting, a trade represents BOTH a buy of one asset AND a sell
 * of another (the symbol's base + quote). v1 emits a single
 * NormalizedTransaction with the cost (in quote currency) and lets V2's
 * SUSPENSE default rule route it for human review. v1.1 will emit two
 * legs (one per asset) when V2 has trade-routing rules in its yaml.
 */
function normalizeTrade(trade: any, exchangeId: string): NormalizedTransaction {
  const symbol = trade.symbol ?? '';
  const [base, quote] = symbol.split('/');
  const side = trade.side === 'sell' ? 'sell' : 'buy';
  const cost = Number(trade.cost ?? trade.price * trade.amount ?? 0);
  const direction: 'in' | 'out' = side === 'buy' ? 'out' : 'in';

  return {
    id: `trade-${trade.id ?? `${trade.timestamp}-${symbol}-${side}`}`,
    adapter: exchangeId,
    direction,
    type: 'trade',
    amount: cost > 0 ? cost : Number(trade.amount ?? 0),
    currency: (quote || base || 'USD').toUpperCase(),
    description: `${side.toUpperCase()} ${trade.amount ?? ''} ${base ?? ''} @ ${trade.price ?? ''} ${quote ?? ''}`.trim(),
    counterparty: null,
    status: 'CLOSED',
    timestamp: trade.datetime ?? new Date(trade.timestamp ?? Date.now()).toISOString(),
    source_wallet_id: exchangeId,
  };
}

/**
 * Normalize a CCXT Transaction (deposit or withdrawal).
 * https://docs.ccxt.com/#/?id=transaction-structure
 */
function normalizeTransfer(
  tx: any,
  type: 'deposit' | 'withdrawal',
  direction: 'in' | 'out',
  exchangeId: string,
): NormalizedTransaction {
  const currency = String(tx.currency ?? 'BTC').toUpperCase();
  const amount = Number(tx.amount ?? 0);
  const isBtc = currency === 'BTC';

  const base = {
    id: `${type}-${tx.id ?? tx.txid ?? `${tx.timestamp}-${currency}`}`,
    adapter: exchangeId,
    direction,
    type,
    description: tx.network ? `via ${tx.network}` : null,
    counterparty: typeof tx.address === 'string' ? tx.address : null,
    // CCXT statuses: 'ok' | 'pending' | 'failed' | 'canceled'. Map up:
    status:
      tx.status === 'ok' ? 'COMPLETE' : tx.status === 'pending' ? 'PENDING' : (tx.status ?? 'PENDING').toUpperCase(),
    timestamp: tx.datetime ?? new Date(tx.timestamp ?? Date.now()).toISOString(),
    source_wallet_id: exchangeId,
  } as const;

  if (isBtc) {
    return { ...base, amount_sats: Math.round(amount * 100_000_000) };
  }
  return { ...base, amount, currency };
}

// --- Adapter factory -----------------------------------------------------

export function makeCcxtAdapter(config: CcxtAdapterConfig): ProviderAdapter {
  const { slug, exchangeId, displayName, description, tags, popularity, credentialShape, capabilities } = config;
  const credentialFields = buildCredentialFields(exchangeId, credentialShape);

  async function syncByWallets(
    credentials: Record<string, unknown>,
    walletIds: string[],
    cursor: string | null,
  ): Promise<SyncResult> {
    if (walletIds.length === 0) return { transactions: [], next_cursor: null };
    const exchange = await instantiateExchange(exchangeId, credentials);
    const since = cursor ? Number(cursor) : undefined;

    const { transactions, denied } = await fetchAllSince(exchange, exchangeId, since);

    // Cursor = highest timestamp (unix ms) seen across the batch.
    //
    // Note the cursor still advances when a source was skipped, so rows that
    // source would have returned below the new cursor are not picked up if the
    // key later gains the missing permission. Re-reading them needs a
    // reconnect, and `partial` is what makes that visible. Holding the cursor
    // back instead would re-fetch the full history on every sync forever,
    // since a read-only key is the steady state rather than a transient one.
    let maxSeen = since ?? 0;
    for (const tx of transactions) {
      const ts = new Date(tx.timestamp).getTime();
      if (ts > maxSeen) maxSeen = ts;
    }

    transactions.sort((a, b) => (a.timestamp < b.timestamp ? 1 : -1));

    return {
      transactions,
      next_cursor: maxSeen > 0 ? String(maxSeen) : null,
      ...(denied.length > 0 ? { partial: true, denied_sources: denied } : {}),
    };
  }

  async function syncAccountWide(
    credentials: Record<string, unknown>,
    cursor: string | null,
  ): Promise<SyncResult> {
    return syncByWallets(credentials, [slug], cursor);
  }

  return {
    slug,
    displayName,
    description,
    // CCXT exchanges go straight to 'live' , the library is widely used
    // and battle-tested. Per-exchange edge cases get filed as bugs, not
    // gated behind a beta badge that pollutes the picker UI.
    status: 'live',
    category: 'exchange',
    custody: 'custodial',
    tags,
    popularity,
    multiWallet: false, // single synthetic wallet per exchange in v1
    ...(capabilities !== undefined ? { capabilities } : {}),
    credentialFields,
    discoverWallets: buildDiscover(slug, exchangeId),
    syncByWallets,
    syncAccountWide,
  };
}
