/**
 * GENERATED FILE — do not edit by hand.
 * Source: scripts/generate-ccxt-manifest.mjs introspecting ccxt@4.4.30
 * Regenerated: 2026-08-04
 * Total exchanges: 98
 */

export interface CcxtExchangeManifestEntry {
  slug: string;
  exchangeId: string;
  displayName: string;
  description?: string;
  tags: string[];
  popularity: number;
  credentialShape: 'apiKey+secret' | 'apiKey+password+secret' | 'apiKey+secret+uid';
  capabilities: { trades: boolean; deposits: boolean; withdrawals: boolean };
}

export const CCXT_MANIFEST: ReadonlyArray<CcxtExchangeManifestEntry> = [
  {
    slug: "coinbase",
    exchangeId: "coinbase",
    displayName: "Coinbase Advanced",
    description: "Coinbase Advanced (US)",
    tags: ["exchange","us","fiat-on-ramp"],
    popularity: 100,
    credentialShape: "apiKey+secret",
    capabilities: { trades: true, deposits: true, withdrawals: true },
  },
  {
    slug: "binance",
    exchangeId: "binance",
    displayName: "Binance",
    description: "Binance (JP, MT)",
    tags: ["exchange","eu","asia","fiat-on-ramp"],
    popularity: 95,
    credentialShape: "apiKey+secret",
    capabilities: { trades: true, deposits: true, withdrawals: true },
  },
  {
    slug: "kraken",
    exchangeId: "kraken",
    displayName: "Kraken",
    description: "Kraken (US)",
    tags: ["exchange","us","fiat-on-ramp"],
    popularity: 95,
    credentialShape: "apiKey+secret",
    capabilities: { trades: true, deposits: true, withdrawals: true },
  },
  {
    slug: "bybit",
    exchangeId: "bybit",
    displayName: "Bybit",
    description: "Bybit (VG)",
    tags: ["exchange","fiat-on-ramp"],
    popularity: 85,
    credentialShape: "apiKey+secret",
    capabilities: { trades: true, deposits: true, withdrawals: true },
  },
  {
    slug: "okx",
    exchangeId: "okx",
    displayName: "OKX",
    description: "OKX (CN, US)",
    tags: ["exchange","us","fiat-on-ramp"],
    popularity: 82,
    credentialShape: "apiKey+password+secret",
    capabilities: { trades: true, deposits: true, withdrawals: true },
  },
  {
    slug: "gemini",
    exchangeId: "gemini",
    displayName: "Gemini",
    description: "Gemini (US)",
    tags: ["exchange","us"],
    popularity: 75,
    credentialShape: "apiKey+secret",
    capabilities: { trades: true, deposits: false, withdrawals: false },
  },
  {
    slug: "kucoin",
    exchangeId: "kucoin",
    displayName: "KuCoin",
    description: "KuCoin (SC)",
    tags: ["exchange","fiat-on-ramp"],
    popularity: 75,
    credentialShape: "apiKey+password+secret",
    capabilities: { trades: true, deposits: true, withdrawals: true },
  },
  {
    slug: "cryptocom",
    exchangeId: "cryptocom",
    displayName: "Crypto.com",
    description: "Crypto.com (MT)",
    tags: ["exchange","eu","fiat-on-ramp"],
    popularity: 72,
    credentialShape: "apiKey+secret",
    capabilities: { trades: true, deposits: true, withdrawals: true },
  },
  {
    slug: "bitstamp",
    exchangeId: "bitstamp",
    displayName: "Bitstamp",
    description: "Bitstamp (GB)",
    tags: ["exchange","eu","fiat-on-ramp"],
    popularity: 70,
    credentialShape: "apiKey+secret",
    capabilities: { trades: true, deposits: false, withdrawals: true },
  },
  {
    slug: "bitfinex",
    exchangeId: "bitfinex",
    displayName: "Bitfinex",
    description: "Bitfinex (VG)",
    tags: ["exchange"],
    popularity: 65,
    credentialShape: "apiKey+secret",
    capabilities: { trades: true, deposits: false, withdrawals: false },
  },
  {
    slug: "bitget",
    exchangeId: "bitget",
    displayName: "Bitget",
    description: "Bitget (SG)",
    tags: ["exchange","asia","fiat-on-ramp"],
    popularity: 65,
    credentialShape: "apiKey+password+secret",
    capabilities: { trades: true, deposits: true, withdrawals: true },
  },
  {
    slug: "gate",
    exchangeId: "gate",
    displayName: "Gate.io",
    description: "Gate.io (KR)",
    tags: ["exchange","asia","fiat-on-ramp"],
    popularity: 65,
    credentialShape: "apiKey+secret",
    capabilities: { trades: true, deposits: true, withdrawals: true },
  },
  {
    slug: "htx",
    exchangeId: "htx",
    displayName: "HTX",
    description: "HTX (CN)",
    tags: ["exchange","fiat-on-ramp"],
    popularity: 60,
    credentialShape: "apiKey+secret",
    capabilities: { trades: true, deposits: true, withdrawals: true },
  },
  {
    slug: "mexc",
    exchangeId: "mexc",
    displayName: "MEXC Global",
    description: "MEXC Global (SC)",
    tags: ["exchange","fiat-on-ramp"],
    popularity: 60,
    credentialShape: "apiKey+secret",
    capabilities: { trades: true, deposits: true, withdrawals: true },
  },
  {
    slug: "upbit",
    exchangeId: "upbit",
    displayName: "Upbit",
    description: "Upbit (KR)",
    tags: ["exchange","asia","fiat-on-ramp"],
    popularity: 60,
    credentialShape: "apiKey+secret",
    capabilities: { trades: false, deposits: true, withdrawals: true },
  },
  {
    slug: "bingx",
    exchangeId: "bingx",
    displayName: "BingX",
    description: "BingX (US)",
    tags: ["exchange","us","fiat-on-ramp"],
    popularity: 55,
    credentialShape: "apiKey+secret",
    capabilities: { trades: false, deposits: true, withdrawals: true },
  },
  {
    slug: "bitflyer",
    exchangeId: "bitflyer",
    displayName: "bitFlyer",
    description: "bitFlyer (JP)",
    tags: ["exchange","asia","fiat-on-ramp"],
    popularity: 55,
    credentialShape: "apiKey+secret",
    capabilities: { trades: true, deposits: true, withdrawals: true },
  },
  {
    slug: "bithumb",
    exchangeId: "bithumb",
    displayName: "Bithumb",
    description: "Bithumb (KR)",
    tags: ["exchange","asia"],
    popularity: 55,
    credentialShape: "apiKey+secret",
    capabilities: { trades: false, deposits: false, withdrawals: false },
  },
  {
    slug: "coincheck",
    exchangeId: "coincheck",
    displayName: "coincheck",
    description: "coincheck (JP, ID)",
    tags: ["exchange","asia","fiat-on-ramp"],
    popularity: 50,
    credentialShape: "apiKey+secret",
    capabilities: { trades: true, deposits: true, withdrawals: true },
  },
  {
    slug: "hitbtc",
    exchangeId: "hitbtc",
    displayName: "HitBTC",
    description: "HitBTC (HK)",
    tags: ["exchange","asia","fiat-on-ramp"],
    popularity: 50,
    credentialShape: "apiKey+secret",
    capabilities: { trades: true, deposits: true, withdrawals: true },
  },
  {
    slug: "luno",
    exchangeId: "luno",
    displayName: "luno",
    description: "luno (GB, SG, ZA)",
    tags: ["exchange","eu","asia"],
    popularity: 50,
    credentialShape: "apiKey+secret",
    capabilities: { trades: true, deposits: false, withdrawals: false },
  },
  {
    slug: "poloniex",
    exchangeId: "poloniex",
    displayName: "Poloniex",
    description: "Poloniex (US)",
    tags: ["exchange","us","fiat-on-ramp"],
    popularity: 50,
    credentialShape: "apiKey+secret",
    capabilities: { trades: true, deposits: true, withdrawals: true },
  },
  {
    slug: "btcmarkets",
    exchangeId: "btcmarkets",
    displayName: "BTC Markets",
    description: "BTC Markets (AU)",
    tags: ["exchange","fiat-on-ramp"],
    popularity: 45,
    credentialShape: "apiKey+secret",
    capabilities: { trades: true, deposits: true, withdrawals: true },
  },
  {
    slug: "hashkey",
    exchangeId: "hashkey",
    displayName: "HashKey Global",
    description: "HashKey Global (BM)",
    tags: ["exchange","fiat-on-ramp"],
    popularity: 45,
    credentialShape: "apiKey+secret",
    capabilities: { trades: true, deposits: true, withdrawals: true },
  },
  {
    slug: "independentreserve",
    exchangeId: "independentreserve",
    displayName: "Independent Reserve",
    description: "Independent Reserve (AU, NZ)",
    tags: ["exchange"],
    popularity: 45,
    credentialShape: "apiKey+secret",
    capabilities: { trades: true, deposits: false, withdrawals: false },
  },
  {
    slug: "lbank",
    exchangeId: "lbank",
    displayName: "LBank",
    description: "LBank (CN)",
    tags: ["exchange"],
    popularity: 45,
    credentialShape: "apiKey+secret",
    capabilities: { trades: true, deposits: false, withdrawals: false },
  },
  {
    slug: "whitebit",
    exchangeId: "whitebit",
    displayName: "WhiteBit",
    description: "WhiteBit (EE)",
    tags: ["exchange","eu","fiat-on-ramp"],
    popularity: 45,
    credentialShape: "apiKey+secret",
    capabilities: { trades: true, deposits: true, withdrawals: false },
  },
  {
    slug: "hollaex",
    exchangeId: "hollaex",
    displayName: "HollaEx",
    description: "HollaEx (KR)",
    tags: ["exchange","asia","fiat-on-ramp"],
    popularity: 40,
    credentialShape: "apiKey+secret",
    capabilities: { trades: true, deposits: true, withdrawals: true },
  },
  {
    slug: "ace",
    exchangeId: "ace",
    displayName: "ACE",
    description: "ACE (TW)",
    tags: ["exchange","asia"],
    popularity: 35,
    credentialShape: "apiKey+secret",
    capabilities: { trades: true, deposits: false, withdrawals: false },
  },
  {
    slug: "alpaca",
    exchangeId: "alpaca",
    displayName: "Alpaca",
    description: "Alpaca (US)",
    tags: ["exchange","us","fiat-on-ramp"],
    popularity: 35,
    credentialShape: "apiKey+secret",
    capabilities: { trades: true, deposits: true, withdrawals: true },
  },
  {
    slug: "ascendex",
    exchangeId: "ascendex",
    displayName: "AscendEX",
    description: "AscendEX (SG)",
    tags: ["exchange","asia","fiat-on-ramp"],
    popularity: 35,
    credentialShape: "apiKey+secret",
    capabilities: { trades: false, deposits: true, withdrawals: true },
  },
  {
    slug: "bequant",
    exchangeId: "bequant",
    displayName: "Bequant",
    description: "Bequant (MT)",
    tags: ["exchange","eu","fiat-on-ramp"],
    popularity: 35,
    credentialShape: "apiKey+secret",
    capabilities: { trades: true, deposits: true, withdrawals: true },
  },
  {
    slug: "bigone",
    exchangeId: "bigone",
    displayName: "BigONE",
    description: "BigONE (CN)",
    tags: ["exchange","fiat-on-ramp"],
    popularity: 35,
    credentialShape: "apiKey+secret",
    capabilities: { trades: true, deposits: true, withdrawals: true },
  },
  {
    slug: "binancecoinm",
    exchangeId: "binancecoinm",
    displayName: "Binance COIN-M",
    description: "Binance COIN-M (JP, MT)",
    tags: ["exchange","eu","asia","fiat-on-ramp"],
    popularity: 35,
    credentialShape: "apiKey+secret",
    capabilities: { trades: true, deposits: true, withdrawals: true },
  },
  {
    slug: "binanceus",
    exchangeId: "binanceus",
    displayName: "Binance US",
    description: "Binance US (US)",
    tags: ["exchange","us","fiat-on-ramp"],
    popularity: 35,
    credentialShape: "apiKey+secret",
    capabilities: { trades: true, deposits: true, withdrawals: true },
  },
  {
    slug: "binanceusdm",
    exchangeId: "binanceusdm",
    displayName: "Binance USDⓈ-M",
    description: "Binance USDⓈ-M (JP, MT)",
    tags: ["exchange","eu","asia","fiat-on-ramp"],
    popularity: 35,
    credentialShape: "apiKey+secret",
    capabilities: { trades: true, deposits: true, withdrawals: true },
  },
  {
    slug: "bit2c",
    exchangeId: "bit2c",
    displayName: "Bit2C",
    description: "Bit2C (IL)",
    tags: ["exchange"],
    popularity: 35,
    credentialShape: "apiKey+secret",
    capabilities: { trades: true, deposits: false, withdrawals: false },
  },
  {
    slug: "bitbank",
    exchangeId: "bitbank",
    displayName: "bitbank",
    description: "bitbank (JP)",
    tags: ["exchange","asia"],
    popularity: 35,
    credentialShape: "apiKey+secret",
    capabilities: { trades: true, deposits: false, withdrawals: false },
  },
  {
    slug: "bitbns",
    exchangeId: "bitbns",
    displayName: "Bitbns",
    description: "Bitbns (IN)",
    tags: ["exchange","asia","fiat-on-ramp"],
    popularity: 35,
    credentialShape: "apiKey+secret",
    capabilities: { trades: true, deposits: true, withdrawals: true },
  },
  {
    slug: "bitcoincom",
    exchangeId: "bitcoincom",
    displayName: "Bitcoin.com",
    description: "Bitcoin.com (KN)",
    tags: ["exchange","fiat-on-ramp"],
    popularity: 35,
    credentialShape: "apiKey+secret",
    capabilities: { trades: true, deposits: true, withdrawals: true },
  },
  {
    slug: "bitfinex2",
    exchangeId: "bitfinex2",
    displayName: "Bitfinex",
    description: "Bitfinex (VG)",
    tags: ["exchange"],
    popularity: 35,
    credentialShape: "apiKey+secret",
    capabilities: { trades: true, deposits: false, withdrawals: false },
  },
  {
    slug: "bitmart",
    exchangeId: "bitmart",
    displayName: "BitMart",
    description: "BitMart (US, CN, HK, KR)",
    tags: ["exchange","us","asia","fiat-on-ramp"],
    popularity: 35,
    credentialShape: "apiKey+secret+uid",
    capabilities: { trades: true, deposits: true, withdrawals: true },
  },
  {
    slug: "bitmex",
    exchangeId: "bitmex",
    displayName: "BitMEX",
    description: "BitMEX (SC)",
    tags: ["exchange"],
    popularity: 35,
    credentialShape: "apiKey+secret",
    capabilities: { trades: true, deposits: false, withdrawals: false },
  },
  {
    slug: "bitopro",
    exchangeId: "bitopro",
    displayName: "BitoPro",
    description: "BitoPro (TW)",
    tags: ["exchange","asia","fiat-on-ramp"],
    popularity: 35,
    credentialShape: "apiKey+secret",
    capabilities: { trades: true, deposits: true, withdrawals: true },
  },
  {
    slug: "bitrue",
    exchangeId: "bitrue",
    displayName: "Bitrue",
    description: "Bitrue (SG)",
    tags: ["exchange","asia","fiat-on-ramp"],
    popularity: 35,
    credentialShape: "apiKey+secret",
    capabilities: { trades: true, deposits: true, withdrawals: true },
  },
  {
    slug: "bitso",
    exchangeId: "bitso",
    displayName: "Bitso",
    description: "Bitso (MX)",
    tags: ["exchange","fiat-on-ramp"],
    popularity: 35,
    credentialShape: "apiKey+secret",
    capabilities: { trades: true, deposits: true, withdrawals: false },
  },
  {
    slug: "bitteam",
    exchangeId: "bitteam",
    displayName: "BIT.TEAM",
    description: "BIT.TEAM (UK)",
    tags: ["exchange"],
    popularity: 35,
    credentialShape: "apiKey+secret",
    capabilities: { trades: true, deposits: false, withdrawals: false },
  },
  {
    slug: "bitvavo",
    exchangeId: "bitvavo",
    displayName: "Bitvavo",
    description: "Bitvavo (NL)",
    tags: ["exchange","eu","fiat-on-ramp"],
    popularity: 35,
    credentialShape: "apiKey+secret",
    capabilities: { trades: true, deposits: true, withdrawals: true },
  },
  {
    slug: "bl3p",
    exchangeId: "bl3p",
    displayName: "BL3P",
    description: "BL3P (NL)",
    tags: ["exchange","eu"],
    popularity: 35,
    credentialShape: "apiKey+secret",
    capabilities: { trades: false, deposits: false, withdrawals: false },
  },
  {
    slug: "blofin",
    exchangeId: "blofin",
    displayName: "BloFin",
    description: "BloFin (US)",
    tags: ["exchange","us","fiat-on-ramp"],
    popularity: 35,
    credentialShape: "apiKey+password+secret",
    capabilities: { trades: true, deposits: true, withdrawals: true },
  },
  {
    slug: "btcalpha",
    exchangeId: "btcalpha",
    displayName: "BTC-Alpha",
    description: "BTC-Alpha (US)",
    tags: ["exchange","us","fiat-on-ramp"],
    popularity: 35,
    credentialShape: "apiKey+secret",
    capabilities: { trades: true, deposits: true, withdrawals: true },
  },
  {
    slug: "btcbox",
    exchangeId: "btcbox",
    displayName: "BtcBox",
    description: "BtcBox (JP)",
    tags: ["exchange","asia"],
    popularity: 35,
    credentialShape: "apiKey+secret",
    capabilities: { trades: false, deposits: false, withdrawals: false },
  },
  {
    slug: "btcturk",
    exchangeId: "btcturk",
    displayName: "BTCTurk",
    description: "BTCTurk (TR)",
    tags: ["exchange"],
    popularity: 35,
    credentialShape: "apiKey+secret",
    capabilities: { trades: true, deposits: false, withdrawals: false },
  },
  {
    slug: "cex",
    exchangeId: "cex",
    displayName: "CEX.IO",
    description: "CEX.IO (GB, EU, CY, RU)",
    tags: ["exchange","eu"],
    popularity: 35,
    credentialShape: "apiKey+secret",
    capabilities: { trades: false, deposits: false, withdrawals: false },
  },
  {
    slug: "coinbaseadvanced",
    exchangeId: "coinbaseadvanced",
    displayName: "Coinbase Advanced",
    description: "Coinbase Advanced (US)",
    tags: ["exchange","us","fiat-on-ramp"],
    popularity: 35,
    credentialShape: "apiKey+secret",
    capabilities: { trades: true, deposits: true, withdrawals: true },
  },
  {
    slug: "coinbaseexchange",
    exchangeId: "coinbaseexchange",
    displayName: "Coinbase Exchange",
    description: "Coinbase Exchange (US)",
    tags: ["exchange","us","fiat-on-ramp"],
    popularity: 35,
    credentialShape: "apiKey+password+secret",
    capabilities: { trades: true, deposits: true, withdrawals: true },
  },
  {
    slug: "coinbaseinternational",
    exchangeId: "coinbaseinternational",
    displayName: "Coinbase International",
    description: "Coinbase International (US)",
    tags: ["exchange","us","fiat-on-ramp"],
    popularity: 35,
    credentialShape: "apiKey+password+secret",
    capabilities: { trades: true, deposits: true, withdrawals: true },
  },
  {
    slug: "coincatch",
    exchangeId: "coincatch",
    displayName: "CoinCatch",
    description: "CoinCatch (VG)",
    tags: ["exchange","fiat-on-ramp"],
    popularity: 35,
    credentialShape: "apiKey+password+secret",
    capabilities: { trades: true, deposits: true, withdrawals: true },
  },
  {
    slug: "coinex",
    exchangeId: "coinex",
    displayName: "CoinEx",
    description: "CoinEx (CN)",
    tags: ["exchange","fiat-on-ramp"],
    popularity: 35,
    credentialShape: "apiKey+secret",
    capabilities: { trades: true, deposits: true, withdrawals: true },
  },
  {
    slug: "coinlist",
    exchangeId: "coinlist",
    displayName: "Coinlist",
    description: "Coinlist (US)",
    tags: ["exchange","us"],
    popularity: 35,
    credentialShape: "apiKey+secret",
    capabilities: { trades: true, deposits: false, withdrawals: false },
  },
  {
    slug: "coinmate",
    exchangeId: "coinmate",
    displayName: "CoinMate",
    description: "CoinMate (GB, CZ, EU)",
    tags: ["exchange","eu"],
    popularity: 35,
    credentialShape: "apiKey+secret+uid",
    capabilities: { trades: true, deposits: false, withdrawals: false },
  },
  {
    slug: "coinone",
    exchangeId: "coinone",
    displayName: "CoinOne",
    description: "CoinOne (KR)",
    tags: ["exchange","asia"],
    popularity: 35,
    credentialShape: "apiKey+secret",
    capabilities: { trades: true, deposits: false, withdrawals: false },
  },
  {
    slug: "coinsph",
    exchangeId: "coinsph",
    displayName: "Coins.ph",
    description: "Coins.ph (PH)",
    tags: ["exchange","asia","fiat-on-ramp"],
    popularity: 35,
    credentialShape: "apiKey+secret",
    capabilities: { trades: true, deposits: true, withdrawals: true },
  },
  {
    slug: "coinspot",
    exchangeId: "coinspot",
    displayName: "CoinSpot",
    description: "CoinSpot (AU)",
    tags: ["exchange"],
    popularity: 35,
    credentialShape: "apiKey+secret",
    capabilities: { trades: true, deposits: false, withdrawals: false },
  },
  {
    slug: "currencycom",
    exchangeId: "currencycom",
    displayName: "Currency.com",
    description: "Currency.com (BY)",
    tags: ["exchange","fiat-on-ramp"],
    popularity: 35,
    credentialShape: "apiKey+secret",
    capabilities: { trades: true, deposits: true, withdrawals: true },
  },
  {
    slug: "delta",
    exchangeId: "delta",
    displayName: "Delta Exchange",
    description: "Delta Exchange (VC)",
    tags: ["exchange"],
    popularity: 35,
    credentialShape: "apiKey+secret",
    capabilities: { trades: true, deposits: false, withdrawals: false },
  },
  {
    slug: "deribit",
    exchangeId: "deribit",
    displayName: "Deribit",
    description: "Deribit (NL)",
    tags: ["exchange","eu","fiat-on-ramp"],
    popularity: 35,
    credentialShape: "apiKey+secret",
    capabilities: { trades: true, deposits: true, withdrawals: true },
  },
  {
    slug: "digifinex",
    exchangeId: "digifinex",
    displayName: "DigiFinex",
    description: "DigiFinex (SG)",
    tags: ["exchange","asia","fiat-on-ramp"],
    popularity: 35,
    credentialShape: "apiKey+secret",
    capabilities: { trades: true, deposits: true, withdrawals: true },
  },
  {
    slug: "exmo",
    exchangeId: "exmo",
    displayName: "EXMO",
    description: "EXMO (LT)",
    tags: ["exchange","eu","fiat-on-ramp"],
    popularity: 35,
    credentialShape: "apiKey+secret",
    capabilities: { trades: true, deposits: true, withdrawals: true },
  },
  {
    slug: "fmfwio",
    exchangeId: "fmfwio",
    displayName: "FMFW.io",
    description: "FMFW.io (KN)",
    tags: ["exchange","fiat-on-ramp"],
    popularity: 35,
    credentialShape: "apiKey+secret",
    capabilities: { trades: true, deposits: true, withdrawals: true },
  },
  {
    slug: "gateio",
    exchangeId: "gateio",
    displayName: "Gate.io",
    description: "Gate.io (KR)",
    tags: ["exchange","asia","fiat-on-ramp"],
    popularity: 35,
    credentialShape: "apiKey+secret",
    capabilities: { trades: true, deposits: true, withdrawals: true },
  },
  {
    slug: "huobi",
    exchangeId: "huobi",
    displayName: "HTX",
    description: "HTX (CN)",
    tags: ["exchange","fiat-on-ramp"],
    popularity: 35,
    credentialShape: "apiKey+secret",
    capabilities: { trades: true, deposits: true, withdrawals: true },
  },
  {
    slug: "huobijp",
    exchangeId: "huobijp",
    displayName: "Huobi Japan",
    description: "Huobi Japan (JP)",
    tags: ["exchange","asia","fiat-on-ramp"],
    popularity: 35,
    credentialShape: "apiKey+secret",
    capabilities: { trades: true, deposits: true, withdrawals: true },
  },
  {
    slug: "indodax",
    exchangeId: "indodax",
    displayName: "INDODAX",
    description: "INDODAX (ID)",
    tags: ["exchange","asia"],
    popularity: 35,
    credentialShape: "apiKey+secret",
    capabilities: { trades: false, deposits: false, withdrawals: false },
  },
  {
    slug: "krakenfutures",
    exchangeId: "krakenfutures",
    displayName: "Kraken Futures",
    description: "Kraken Futures (US)",
    tags: ["exchange","us"],
    popularity: 35,
    credentialShape: "apiKey+secret",
    capabilities: { trades: true, deposits: false, withdrawals: false },
  },
  {
    slug: "kucoinfutures",
    exchangeId: "kucoinfutures",
    displayName: "KuCoin Futures",
    description: "KuCoin Futures (SC)",
    tags: ["exchange","fiat-on-ramp"],
    popularity: 35,
    credentialShape: "apiKey+password+secret",
    capabilities: { trades: true, deposits: true, withdrawals: true },
  },
  {
    slug: "kuna",
    exchangeId: "kuna",
    displayName: "Kuna",
    description: "Kuna (UA)",
    tags: ["exchange","fiat-on-ramp"],
    popularity: 35,
    credentialShape: "apiKey+secret",
    capabilities: { trades: true, deposits: true, withdrawals: true },
  },
  {
    slug: "latoken",
    exchangeId: "latoken",
    displayName: "Latoken",
    description: "Latoken (KY)",
    tags: ["exchange"],
    popularity: 35,
    credentialShape: "apiKey+secret",
    capabilities: { trades: true, deposits: false, withdrawals: false },
  },
  {
    slug: "mercado",
    exchangeId: "mercado",
    displayName: "Mercado Bitcoin",
    description: "Mercado Bitcoin (BR)",
    tags: ["exchange"],
    popularity: 35,
    credentialShape: "apiKey+secret",
    capabilities: { trades: true, deposits: false, withdrawals: false },
  },
  {
    slug: "novadax",
    exchangeId: "novadax",
    displayName: "NovaDAX",
    description: "NovaDAX (BR)",
    tags: ["exchange","fiat-on-ramp"],
    popularity: 35,
    credentialShape: "apiKey+secret",
    capabilities: { trades: true, deposits: true, withdrawals: true },
  },
  {
    slug: "oceanex",
    exchangeId: "oceanex",
    displayName: "OceanEx",
    description: "OceanEx (BS)",
    tags: ["exchange"],
    popularity: 35,
    credentialShape: "apiKey+secret",
    capabilities: { trades: false, deposits: false, withdrawals: false },
  },
  {
    slug: "okcoin",
    exchangeId: "okcoin",
    displayName: "OKCoin",
    description: "OKCoin (CN, US)",
    tags: ["exchange","us","fiat-on-ramp"],
    popularity: 35,
    credentialShape: "apiKey+password+secret",
    capabilities: { trades: true, deposits: true, withdrawals: true },
  },
  {
    slug: "oxfun",
    exchangeId: "oxfun",
    displayName: "OXFUN",
    description: "OXFUN (PA)",
    tags: ["exchange","fiat-on-ramp"],
    popularity: 35,
    credentialShape: "apiKey+secret",
    capabilities: { trades: true, deposits: true, withdrawals: true },
  },
  {
    slug: "p2b",
    exchangeId: "p2b",
    displayName: "p2b",
    description: "p2b (LT)",
    tags: ["exchange","eu"],
    popularity: 35,
    credentialShape: "apiKey+secret",
    capabilities: { trades: true, deposits: false, withdrawals: false },
  },
  {
    slug: "paymium",
    exchangeId: "paymium",
    displayName: "Paymium",
    description: "Paymium (FR, EU)",
    tags: ["exchange","eu"],
    popularity: 35,
    credentialShape: "apiKey+secret",
    capabilities: { trades: false, deposits: false, withdrawals: false },
  },
  {
    slug: "phemex",
    exchangeId: "phemex",
    displayName: "Phemex",
    description: "Phemex (CN)",
    tags: ["exchange","fiat-on-ramp"],
    popularity: 35,
    credentialShape: "apiKey+secret",
    capabilities: { trades: true, deposits: true, withdrawals: true },
  },
  {
    slug: "poloniexfutures",
    exchangeId: "poloniexfutures",
    displayName: "Poloniex Futures",
    description: "Poloniex Futures (US)",
    tags: ["exchange","us"],
    popularity: 35,
    credentialShape: "apiKey+password+secret",
    capabilities: { trades: true, deposits: false, withdrawals: false },
  },
  {
    slug: "probit",
    exchangeId: "probit",
    displayName: "ProBit",
    description: "ProBit (SC, KR)",
    tags: ["exchange","asia","fiat-on-ramp"],
    popularity: 35,
    credentialShape: "apiKey+secret",
    capabilities: { trades: true, deposits: true, withdrawals: true },
  },
  {
    slug: "timex",
    exchangeId: "timex",
    displayName: "TimeX",
    description: "TimeX (AU)",
    tags: ["exchange","fiat-on-ramp"],
    popularity: 35,
    credentialShape: "apiKey+secret",
    capabilities: { trades: true, deposits: true, withdrawals: true },
  },
  {
    slug: "tokocrypto",
    exchangeId: "tokocrypto",
    displayName: "Tokocrypto",
    description: "Tokocrypto (ID)",
    tags: ["exchange","asia","fiat-on-ramp"],
    popularity: 35,
    credentialShape: "apiKey+secret",
    capabilities: { trades: true, deposits: true, withdrawals: true },
  },
  {
    slug: "tradeogre",
    exchangeId: "tradeogre",
    displayName: "tradeogre",
    description: "tradeogre",
    tags: ["exchange"],
    popularity: 35,
    credentialShape: "apiKey+secret",
    capabilities: { trades: false, deposits: false, withdrawals: false },
  },
  {
    slug: "wavesexchange",
    exchangeId: "wavesexchange",
    displayName: "Waves.Exchange",
    description: "Waves.Exchange (CH)",
    tags: ["exchange","eu"],
    popularity: 35,
    credentialShape: "apiKey+secret",
    capabilities: { trades: true, deposits: false, withdrawals: false },
  },
  {
    slug: "wazirx",
    exchangeId: "wazirx",
    displayName: "WazirX",
    description: "WazirX (IN)",
    tags: ["exchange","asia","fiat-on-ramp"],
    popularity: 35,
    credentialShape: "apiKey+secret",
    capabilities: { trades: false, deposits: true, withdrawals: true },
  },
  {
    slug: "woo",
    exchangeId: "woo",
    displayName: "WOO X",
    description: "WOO X (KY)",
    tags: ["exchange","fiat-on-ramp"],
    popularity: 35,
    credentialShape: "apiKey+secret",
    capabilities: { trades: true, deposits: true, withdrawals: true },
  },
  {
    slug: "xt",
    exchangeId: "xt",
    displayName: "XT",
    description: "XT (SC)",
    tags: ["exchange","fiat-on-ramp"],
    popularity: 35,
    credentialShape: "apiKey+secret",
    capabilities: { trades: true, deposits: true, withdrawals: true },
  },
  {
    slug: "yobit",
    exchangeId: "yobit",
    displayName: "YoBit",
    description: "YoBit (RU)",
    tags: ["exchange"],
    popularity: 35,
    credentialShape: "apiKey+secret",
    capabilities: { trades: true, deposits: false, withdrawals: false },
  },
  {
    slug: "zaif",
    exchangeId: "zaif",
    displayName: "Zaif",
    description: "Zaif (JP)",
    tags: ["exchange","asia"],
    popularity: 35,
    credentialShape: "apiKey+secret",
    capabilities: { trades: false, deposits: false, withdrawals: false },
  },
  {
    slug: "zonda",
    exchangeId: "zonda",
    displayName: "Zonda",
    description: "Zonda (EE)",
    tags: ["exchange","eu"],
    popularity: 35,
    credentialShape: "apiKey+secret",
    capabilities: { trades: true, deposits: false, withdrawals: false },
  },
];
