/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnlockRouteImport } from './routes/unlock'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as RecoverRouteImport } from './routes/recover'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as OpenSourceRouteImport } from './routes/open-source'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConnectStealthRouteImport } from './routes/connect/stealth'

const UnlockRoute = UnlockRouteImport.update({
  id: '/unlock',
  path: '/unlock',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverRoute = RecoverRouteImport.update({
  id: '/recover',
  path: '/recover',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const OpenSourceRoute = OpenSourceRouteImport.update({
  id: '/open-source',
  path: '/open-source',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectStealthRoute = ConnectStealthRouteImport.update({
  id: '/stealth',
  path: '/stealth',
  getParentRoute: () => ConnectRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/connect': typeof ConnectRouteWithChildren
  '/docs': typeof DocsRoute
  '/integrations': typeof IntegrationsRoute
  '/login': typeof LoginRoute
  '/open-source': typeof OpenSourceRoute
  '/pricing': typeof PricingRoute
  '/recover': typeof RecoverRoute
  '/signup': typeof SignupRoute
  '/unlock': typeof UnlockRoute
  '/connect/stealth': typeof ConnectStealthRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/connect': typeof ConnectRouteWithChildren
  '/docs': typeof DocsRoute
  '/integrations': typeof IntegrationsRoute
  '/login': typeof LoginRoute
  '/open-source': typeof OpenSourceRoute
  '/pricing': typeof PricingRoute
  '/recover': typeof RecoverRoute
  '/signup': typeof SignupRoute
  '/unlock': typeof UnlockRoute
  '/connect/stealth': typeof ConnectStealthRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/connect': typeof ConnectRouteWithChildren
  '/docs': typeof DocsRoute
  '/integrations': typeof IntegrationsRoute
  '/login': typeof LoginRoute
  '/open-source': typeof OpenSourceRoute
  '/pricing': typeof PricingRoute
  '/recover': typeof RecoverRoute
  '/signup': typeof SignupRoute
  '/unlock': typeof UnlockRoute
  '/connect/stealth': typeof ConnectStealthRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/connect'
    | '/docs'
    | '/integrations'
    | '/login'
    | '/open-source'
    | '/pricing'
    | '/recover'
    | '/signup'
    | '/unlock'
    | '/connect/stealth'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/connect'
    | '/docs'
    | '/integrations'
    | '/login'
    | '/open-source'
    | '/pricing'
    | '/recover'
    | '/signup'
    | '/unlock'
    | '/connect/stealth'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/connect'
    | '/docs'
    | '/integrations'
    | '/login'
    | '/open-source'
    | '/pricing'
    | '/recover'
    | '/signup'
    | '/unlock'
    | '/connect/stealth'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRoute
  ConnectRoute: typeof ConnectRouteWithChildren
  DocsRoute: typeof DocsRoute
  IntegrationsRoute: typeof IntegrationsRoute
  LoginRoute: typeof LoginRoute
  OpenSourceRoute: typeof OpenSourceRoute
  PricingRoute: typeof PricingRoute
  RecoverRoute: typeof RecoverRoute
  SignupRoute: typeof SignupRoute
  UnlockRoute: typeof UnlockRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unlock': {
      id: '/unlock'
      path: '/unlock'
      fullPath: '/unlock'
      preLoaderRoute: typeof UnlockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover': {
      id: '/recover'
      path: '/recover'
      fullPath: '/recover'
      preLoaderRoute: typeof RecoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/open-source': {
      id: '/open-source'
      path: '/open-source'
      fullPath: '/open-source'
      preLoaderRoute: typeof OpenSourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect/stealth': {
      id: '/connect/stealth'
      path: '/stealth'
      fullPath: '/connect/stealth'
      preLoaderRoute: typeof ConnectStealthRouteImport
      parentRoute: typeof ConnectRoute
    }
  }
}

interface ConnectRouteChildren {
  ConnectStealthRoute: typeof ConnectStealthRoute
}

const ConnectRouteChildren: ConnectRouteChildren = {
  ConnectStealthRoute: ConnectStealthRoute,
}

const ConnectRouteWithChildren =
  ConnectRoute._addFileChildren(ConnectRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRoute,
  ConnectRoute: ConnectRouteWithChildren,
  DocsRoute: DocsRoute,
  IntegrationsRoute: IntegrationsRoute,
  LoginRoute: LoginRoute,
  OpenSourceRoute: OpenSourceRoute,
  PricingRoute: PricingRoute,
  RecoverRoute: RecoverRoute,
  SignupRoute: SignupRoute,
  UnlockRoute: UnlockRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
