-- OUT-OF-ORDER-OK: this file was renumbered to 20260909010000_anon_sequence_function_revoke.sql
-- because its original timestamp (20260902030000) fell below the dev migration maximum at the
-- time of rebase. This tombstone is intentionally empty. Supabase applies it as a no-op.
-- All content and assertions live in the correctly-numbered file above.
