-- This file has been superseded.
--
-- Version 20260721120000 is already recorded in the dev migration ledger
-- (revoke_anon_authenticated_agent_rpc_grants). A second file at the same
-- version is skipped silently on dev and would half-apply on prod.
--
-- The actual migration content lives at:
--   20260723120000_or_create_platform_require_authenticated_caller.sql
--
-- This file is intentionally empty (no SQL) so it is a safe no-op if
-- Supabase CLI encounters it on an environment where 20260721120000 is
-- not yet applied.
